server:
  port: 8189
  servlet:
    context-path: /
    session:
        timeout: 21600
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          temp:
            use_jdbc_metadata_defaults: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: { url }
    username: { username }
    password: { password }

